name: GitHub Actions Demo
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

  
jobs:
  Test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: python test.py
  Test-MacOS:
    runs-on: macOS-latest
    steps:
      - run: python test.py
  Test-Windows:
    runs-on: windows-latest
    steps:
      - run: python test.py
